### ISSUE TITLE
[Staging] Loading emergencies fail with 500 

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-frontend#1088]
## Issue
Loading an emergency like <> fails with a 500 from the server. 

### On the backend
http://localhost:8000/api/v2/event/3892/ returns a 500 with:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ifrc/go-api/api/drf_views.py", line 259, in retrieve
    instance = Event.objects.get(pk=pk)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
api.models.Event.DoesNotExist: Event matching query does not exist.
```

### On the front-end
``
emergency.js:87 Uncaught TypeError: Cannot read property 'parent_event' of undefined
    at Emergency.UNSAFE_componentWillReceiveProps (emergency.js:87)
    at callComponentWillReceiveProps (react-dom.development.js:14298)
    at updateClassInstance (react-dom.development.js:14511)
    at updateClassComponent (react-dom.development.js:18420)
    at beginWork$1 (react-dom.development.js:20186)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25780)
    at performUnitOfWork (react-dom.development.js:24698)
``

## URL
* Pull go-api `develop` and go-frontend `develop` locally. And go to any emergency page like http://localhost:3001/emergencies/3892#details

## Steps to reproduce
* Follow above

## Expected behaviour
The emergency page should open without errors

## Criticality/Urgency
This is now a blocker to test response docs ordering and to reliably test the tabs functionality.

cc @batpad @necoline @teklal @GregoryHorvath

**Comment by batpad** [comment]
This was merged and fixed. Closing to clean up noise.
